CREATE USER 'Professor' IDENTIFIED '1234'
GRANT ALL PRIVILEGES ON *.* TO 'Professor'

CREATE USER 'Aluno' IDENTIFIED '1234'
GRANT ALL PRIVILEGES ON alunos TO 'Aluno'

REVOKE CREATE, DROP ON *.* FROM 'Professor'