

CREATE USER 'Professor' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON tarefa TO 'Professor';

CREATE USER  'Monitor' IDENTIFIED  BY '1234';
GRANT INSERT, SELECT, UPDATE, DELETE ON taefa.alunos TO 'Monitor';

REVOKE CREATE, DROP ON tarefa FROM 'Professor';

SHOW GRANTS FOR Professor;

SHOW GRANTS FOR Monitor;